# Generated by Django 5.1.5 on 2025-01-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50, null=True, verbose_name='성별'),
        ),
    ]
