# Generated by Django 5.1.5 on 2025-01-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/%Y/%m/%d', verbose_name='프로필 사진'),
        ),
    ]
